// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKl4vqE6Ioup_fxARY1TYOWKVN0tkkY2s',
    appId: '1:876778171349:web:1eaade95f39259f82aeb5c',
    messagingSenderId: '876778171349',
    projectId: 'flutterapp-4110f',
    authDomain: 'flutterapp-4110f.firebaseapp.com',
    databaseURL: 'https://flutterapp-4110f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-4110f.appspot.com',
    measurementId: 'G-FKBLBRFY0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALqc_lzlayVQBrAAgzECn7NMeB4uzJq8I',
    appId: '1:876778171349:android:5e8a2feaaff05e802aeb5c',
    messagingSenderId: '876778171349',
    projectId: 'flutterapp-4110f',
    databaseURL: 'https://flutterapp-4110f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-4110f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DeHHPQE_aXcofLnjlm9Y_fWrtkgpvlU',
    appId: '1:876778171349:ios:3016216d9b186f552aeb5c',
    messagingSenderId: '876778171349',
    projectId: 'flutterapp-4110f',
    databaseURL: 'https://flutterapp-4110f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-4110f.appspot.com',
    iosClientId: '876778171349-26991agc3p1j460j110d5ektfdn97s62.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter2App',
  );
}
